ShuttleBuilder/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.shortcuts import render
from django.conf import settings
from django.views.i18n import JavaScriptCatalog

urlpatterns = [
    re_path('sdc_view/sdc_tools/', include('sdc_tools.sdc_urls')),
    re_path('sdc_view/sdc_user/', include('sdc_user.sdc_urls')),
    # scd view below
    path('sdc_view/main_app/', include('main_app.sdc_urls')),
    path('sdc_view/main_app/', include('file_handler.urls')),

    path('admin/', admin.site.urls),
]
def index(request):
    return render(request, 'index.html', {'VERSION': settings.VERSION})

urlpatterns += [
    re_path(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('', index, name='sdc_index'),
    re_path('~.*', index, name='sdc_index_2'),
]

file_handler/urls.py
from django.urls import path, re_path
from . import views

# Do not add an app_name to this file

urlpatterns = [
    # scd view below
    path('download/file_exporter_task.vbs', views.DownloadVbs.as_view(), name='shuttle_task.vbs'),
    path('download/shuttle.service', views.DownloadService.as_view(), name='file_shuttle.service'),

]

file_handler/models.py
from django.db import models

# Create your models here.

main_app/models.py
import glob
import os
import re
import shutil
import subprocess

from django.conf import settings
from django.utils import timezone
from sdc_core.sdc_extentions.models import SdcModel
from sdc_core.sdc_extentions.forms import AbstractSearchForm
from django.template.loader import render_to_string
from sdc_core.sdc_extentions.search import handle_search_form
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User
from django.db.models import signals
from django.template import Template, Context

def create_user(sender, instance, created, **kwargs):
    """Create ElnUser for every new User."""
    if created:
        ElnUser.objects.create(user=instance)


signals.post_save.connect(create_user, sender=User, weak=False,
                          dispatch_uid='models.create_eln_user_profile')


class ElnUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    token = models.CharField(max_length=255, default='')
    is_eln_user = models.BooleanField(default=False)


# Create your models here.

class ElnConnectionSearchForm(AbstractSearchForm):
    CHOICES = (("url", "Url"), ("active", "Active"),)
    PLACEHOLDER = ""
    DEFAULT_CHOICES = CHOICES[0][0]
    SEARCH_FIELDS = ("url",)


class ElnConnection(models.Model, SdcModel):
    edit_form = "main_app.forms.ElnConnectionForm"
    create_form = "main_app.forms.ElnConnectionForm"
    html_list_template = "main_app/models/ElnConnection/ElnConnection_list.html"
    html_detail_template = "main_app/models/ElnConnection/ElnConnection_details.html"

    url = models.URLField(_('Eln connection!'))
    active = models.BooleanField()
    token = models.CharField(default=None, null=True, blank=True, max_length=255)
    device = models.IntegerField(default=0)

    def identifier(self):
        return f'URL: {self.url}'

    @classmethod
    def render(cls, template_name, context=None, request=None, using=None):
        if template_name == cls.html_list_template:
            sf = ElnConnectionSearchForm(data=context.get("filter", {}))
            context = context | handle_search_form(context["instances"], sf, range=10)
        return render_to_string(template_name=template_name, context=context, request=request, using=using)

    @classmethod
    def is_authorised(cls, user, action, obj):
        return True

    @classmethod
    def get_queryset(cls, user, action, obj):
        return cls.objects.all()

    @classmethod
    def get_active(cls):
        (instance, c) = ElnConnection.objects.get_or_create(active=True)
        if c:
            instance.url = settings.ELN_URL
            instance.save()
        return instance


class GitInstanceSearchForm(AbstractSearchForm):
    CHOICES = (("url", "Url"), ("branch", "Branch"),)
    PLACEHOLDER = ""
    DEFAULT_CHOICES = CHOICES[0][0]
    SEARCH_FIELDS = ("url", "branch")


class GitInstance(models.Model, SdcModel):
    edit_form = "main_app.forms.GitInstanceForm"
    create_form = "main_app.forms.GitInstanceForm"
    html_list_template = "main_app/models/GitInstance/GitInstance_list.html"
    html_detail_template = "main_app/models/GitInstance/GitInstance_details.html"
    name = models.CharField(help_text=_('Unique name of the git repo. This name cannot be changed!'), unique=True,
                            max_length=50)
    url = models.CharField(help_text=_('URL to the git repo.'), default='', max_length=255)
    branch = models.CharField(_('Commit Or Branch'), help_text=_('Enter the branch name or commit ID.'), max_length=255,
                              default='main')
    is_active = models.BooleanField(default=False)
    last_reload = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.name

    def get_path(self):
        folder_name = re.sub(r'[^a-zA-Z0-9]', '_', self.name)
        file_paths = os.path.join('./projects/git_repos/', folder_name)
        new_repo = glob.glob(os.path.join(file_paths, '*'))
        if len(new_repo) > 0:
            new_repo = os.path.abspath(new_repo[0])
        else:
            new_repo = None

        return (file_paths, new_repo)

    @classmethod
    def get_active(self):
        try:
            return GitInstance.objects.get(is_active=True)
        except GitInstance.MultipleObjectsReturned:
            GitInstance.objects.filter(is_active=True).update(is_active=False)
            return None
        except:
            return None

    def set_active(self):
        GitInstance.objects.filter(is_active=True).update(is_active=False)
        self.is_active = True
        self.save()

    def git_reload(self):
        file_paths, x = self.get_path()
        shutil.rmtree(os.path.join(file_paths), ignore_errors=True)
        os.makedirs(file_paths, exist_ok=True)
        abs_path = os.path.abspath(file_paths)
        p = subprocess.Popen(['git', 'clone', self.url], cwd=abs_path)
        p_status = p.wait()
        if p_status != 0:
            raise Exception(_("Url cannot be cloned: %s") % self.url)
        x, abs_path = self.get_path()
        p = subprocess.Popen(['git', 'checkout', self.branch], cwd=abs_path)
        p_status = p.wait()
        if p_status != 0:
            raise Exception(_("Branch or ID cannot be checked out: %s") % self.branch)
        files = glob.glob(os.path.join(file_paths, '*', '.git'))
        for f in files:
            shutil.rmtree(f)
        files = glob.glob(os.path.join(file_paths, '*', 'bin'))
        for f in files:
            shutil.rmtree(f)

        self.last_reload = timezone.now()
        self.save()

    @classmethod
    def render(cls, template_name, context=None, request=None, using=None):
        if template_name == cls.html_list_template:
            sf = GitInstanceSearchForm(data=context.get("filter", {}))
            context = context | handle_search_form(context["instances"], sf, range=10)
        return render_to_string(template_name=template_name, context=context, request=request, using=using)

    @classmethod
    def is_authorised(cls, user, action, obj):
        return True

    @classmethod
    def get_queryset(cls, user, action, obj):
        return cls.objects.all()


class ShuttleInstanceSearchForm(AbstractSearchForm):
    CHOICES = (
        ('name', _('Name')), ('user', _('User')), ('efw_type', _('Type')), ('src', _('Source')),
        ('dst', _('Destination')),
        ('architecture', _('Architecture')))
    PLACEHOLDER = _('Name, Type, Source, Destination')
    DEFAULT_CHOICES = CHOICES[0][0]
    SEARCH_FIELDS = ('name', 'user', 'efw_type', 'src', 'dst', 'architecture')


TYPE_CHOISES = (
    ('file', _('File')),
    ('folder', _('Folder')),
    ('zip', _('ZIP')),
    ('tar', _('TAR')),
    ('flat_tar', _('Flat TAR'))
)

SYSTEM_CHOISES = (
    ('win_i386', _('Windows i386')),
    ('win_64', _('Windows 64 Bit')),
    ('ubuntu_64', _('Ubuntu 64 Bit')),
    ('raspberry_pi_6', _('Raspberry Pi ARMv6')),
    ('raspberry_pi_7', _('Raspberry Pi ARMv7')),
    ('raspberry_pi_64', _('Raspberry Pi ARM 64 Bit')),
)
TRANSFER_CHOISES = (
    ('webdav', _('WebDAV')),
    ('sftp', _('SFTP')),
)


class ShuttleInstance(models.Model, SdcModel):
    edit_form = "main_app.forms.ShuttleInstanceForm"
    create_form = "main_app.forms.ShuttleInstanceForm"
    html_list_template = "main_app/models/ShuttleInstance/ShuttleInstance_list.html"
    html_detail_template = "main_app/models/ShuttleInstance/ShuttleInstance_details.html"

    name = models.CharField(help_text=_('Unique name of the Shuttle instance. This name cannot be changed!'),
                            max_length=50,
                            unique=True)
    user = models.CharField(help_text=_("WebDAV or STFP User"), max_length=50, default="")
    password = models.CharField(help_text=_("WebDAV or STFP Password"), max_length=100)
    transfer = models.CharField(_('Transfer protocol'),
                                help_text=_("You can either use the WebDAV protocol or the SFTP protocol"),
                                max_length=255, choices=TRANSFER_CHOISES, default=TRANSFER_CHOISES[0][0])
    src = models.CharField(help_text=_(
        "Source directory to monitor."),
        max_length=255)
    dst = models.CharField(help_text=_("""WebDAV or SFTP destination URL. If the destination is on the lsdf, the URL should be as follows:<br>
        <span style="margin-left: 20px; font-weight: 800;">SFTP</span>: os-login.lsdf.kit.edu/[OE]/[inst]/projects/[PROJECT_PATH]/<br>
        <span style="margin-left: 20px; font-weight: 800;">WebDAV</span>: https://os-webdav.lsdf.kit.edu/[OE]/[inst]/projects/[PROJECT_PATH]/<br>

                    <span style="margin-left: 30px;">[OE]-Organisationseinheit, z.B. kit.</span><br>
                    <span style="margin-left: 30px;">[inst]-Institut-Name, z.B. ioc, scc, ikp, imk-asf etc.</span><br>
                    <span style="margin-left: 30px;">[USERNAME]-User-Name z.B. xy1234, bs_abcd etc.</span><br>
                    <span style="margin-left: 30px;">[PROJECT_PATH]-Path (directory) within the LSDF</span>"""),
                           max_length=255)
    shuttle_type = models.CharField(_('Type'), help_text=_(
        "Type must be 'file', 'folder', 'tar' or 'zip'. The 'file' option means that each file is handled individually, the 'folder' option means that entire folders are transmitted only when all files in them are ready. The options 'tar' ond/or 'zip' sends a folder zipped (or compressed as tar archieve), only when all files in a folder are ready."),
                                    max_length=255, choices=TYPE_CHOISES)
    common_name_parts = models.CharField(_('Common name regex'), blank=True, max_length=255, default="^[A-Za-z]{1,4}", help_text=_(

main_app/forms.py
import re

from jsonschema.exceptions import ValidationError

from main_app.models import ShuttleInstance
from main_app.models import GitInstance
from main_app.models import ElnConnection
from django.forms.models import ModelForm


# Form Model ElnConnection

class ElnConnectionForm(ModelForm):
    class Meta:
        model = ElnConnection
        fields = "__all__"



# Form Model GitInstance

class GitInstanceForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        instance = self.instance
        if instance and instance.pk:
            self.fields['name'].widget.attrs['readonly'] = True


    def clean_name(self):
        instance = self.instance
        if instance and instance.pk:
            return instance.name
        else:
            return self.cleaned_data['name']


    class Meta:
        model = GitInstance
        fields = ['name', 'url', 'branch']

    def generate_filte(self):
        pass



# Form Model ShuttleInstance

class ShuttleInstanceForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        instance = self.instance
        if instance and instance.pk:
            self.fields['name'].widget.attrs['readonly'] = True

    def clean_name(self):
        instance = getattr(self, 'instance', None)
        if instance and instance.pk:
            return instance.name
        else:
            return self.cleaned_data['name']

    def clean(self):
        cleaned_data = super().clean()
        if cleaned_data['shuttle_type'] == 'flat_tar':
            common_name_parts = cleaned_data.get('common_name_parts', '')
            if len(common_name_parts) == 0:
                self.add_error('common_name_parts', ValidationError('Common name regex must not be empty if the send type is set to flat_tar'))

            try:
                re.compile(fr"{common_name_parts}")
            except:
                self.add_error('common_name_parts', ValidationError('Common name regex must be a compilable regular expression send type is set to flat_tar'))
        return cleaned_data

    class Meta:
        model = ShuttleInstance
        fields = ['name', 'transfer', 'user', 'password', 'src', 'dst', 'shuttle_type', 'common_name_parts', 'duration', 'architecture']

main_app/views.py
from django.shortcuts import render

# Create your views here.

main_app/templates/main_app/models/ShuttleInstance/ShuttleInstance_details.html
{% load sdc_filter %}

<div class="container-fluid">
    <div class="row">
        <div class="col-8">
            <h3>{{instance}}</h3>
        </div>
        <div class="col-4">
            <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#delete{{instance|to_class_name}}Modal_detail">
                Remove
            </button>
            <!-- Modal -->
            <div class="modal fade" id="delete{{instance|to_class_name}}Modal_detail" tabindex="-1" aria-labelledby="delete{{instance|to_class_name}}Modal_detil_label" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="delete{{instance|to_class_name}}Modal_detil_label">Are you sure</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            Do you want to delete {{instance}}?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button sdc_click="removeInstance" data-instance-pk="{{instance.pk}}" type="button" class="btn btn-danger" data-bs-dismiss="modal">Remove {{instance}}</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

main_app/templates/main_app/models/ShuttleInstance/ShuttleInstance_list.html
{% load sdc_filter %}
{% load i18n %}

<div class="search-view-container">
    <sdc-search-view
            data-range-size="{{ range_size }}"
            data-range-start="{{ range|indexfilter:0 }}"
            data-range-end="{{ range|indexfilter:1 }}"
            data-total-count="{{ total_count }}"
            data-remove-labels="true">
        {% csrf_token %}
        {% include "elements/inline_form.html" with form=search_form %}
    </sdc-search-view>
</div>

<table class="table">
    <tbody>
    {% for instance in instances %}
    {% if forloop.first %}
    <tr>
        <th>Identifier</th>
        <th>Type</th>
        <th>Protocol</th>
        <th>Architecture</th>
        <th>Control</th>
    </tr>
    {% endif %}
    <tr>
        <th class="item-row-name" scope="row">{{ instance.name }}</th>
        <td>{{ instance.get_shuttle_type_display }}</td>
        <td>{{ instance.get_transfer_display }}</td>
        <td>{{ instance.get_architecture_display }}</td>
        <td>
            <a target="_blank" href="{% url 'scd_view_shuttle_download' pk=instance.pk %}" class="btn btn-info" data-toggle="tooltip" data-placement="left" title="{% trans 'Download Executable!' %}">
                <i class="bi bi-download"></i>
            </a>
            <a class="btn btn-dark navigation-links" href="/~shuttle-instance-edit&pk={{instance.pk}}">
                <i class="bi bi-wrench-adjustable-circle"></i>
            </a>

            <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#delete-model-modal-{{instance.pk}}">
                <i class="bi bi-trash"></i>
            </button>
            <div class="modal fade" id="delete-model-modal-{{instance.pk}}" tabindex="-1" aria-label="Delete model {{instance.pk}}" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="delete-model-modal-{{instance.pk}}-label">Are you sure</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            Do you want to delete {{instance}}?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button sdc_click="removeInstance" data-instance-pk="{{instance.pk}}" type="button" class="btn btn-danger" data-bs-dismiss="modal">Remove {{instance}}</button>
                        </div>
                    </div>
                </div>
            </div>
        </td>
    </tr>
    </tbody>
    {% endfor %}
</table>